apiVersion: v1
kind: Pod
metadata:
  name: tilley-time-webserver
  labels:
    app: tilley-time-web
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: tilley-content
      mountPath: /usr/share/nginx/html/index.html
      subPath: index.html
    - name: tilley-content
      mountPath: /usr/share/nginx/html/style.css
      subPath: style.css
    - name: tilley-content
      mountPath: /usr/share/nginx/html/script.js
      subPath: script.js
  volumes:
  - name: tilley-content
    configMap:
      name: tilley-web-files
